### ISSUE TITLE
Explain what nodes are

### ISSUE THREAD

**Issue by andimarafioti** [hpc-unibe-ch/hpc-unibe-ch.github.io#16]
**Is your feature request related to a current shortcoming? Please describe.**

I had a student using UBELIX without understanding what nodes are and how to use them (aka, running everything on the submit node). There are two mentions in the guide to not doing this: 
    

1. at the end of the FAQ: "DO NOT run resource-intensive computations directly on the front-end server (submit hosts). This will have a negative impact on the performance of the whole cluster. Instead, submit such computations as a job to the cluster" 
But there the wording is unclear, I would change it for "directly on the submit node".

2. in the quick start guide: "Finally, it’s time for your first job. To do some work on the cluster, you require certain resources (e.g. CPUs and memory) and a description of the computations to be done"
But there it doesn't say that you shouldn't use the submit node even when you can.

**Describe the solution you'd like**
Change the wording in the FAQ and add a small section/subsection to the quick start guide about what nodes are and what you should and should not do in the submit node.

**Comment by mrolli** [comment]
@andimarafioti Please see commit in #18, what do you think?
