### ISSUE TITLE
Partitions/QoS

### ISSUE THREAD

**Issue by NadjaKry** [hpc-unibe-ch/hpc-unibe-ch.github.io#24]
Dear HPC team,

can you please check the table with QoS description :
I think there should be not "bdw_debug" but "job_bdw_debug", and the same for bdw_short.

Best,
Nadja

**Comment by mrolli** [comment]
Thank you for your issue report. You are very right and the bug has been fixed 5 months ago in a7c08b599266e267994770073b42b632a3d9bc81

Being involved in docs again, next time your inquiry will be fixed much faster. 😀
